parser: babel-eslint

env:
  browser: true
  node: true
  es6: true

globals:
  atom: true

extends:
  - eslint:recommended
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype

plugins:
  - flowtype
  - prettier

rules:
  prettier/prettier: error
